---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgB0nSGGmxeH0woMLcWb2I/rdLcGGHyJQ6uPMlm59+r5DS36HWaY/CPqMagXLBXAqxtgPABBZ5+vnikF478w7KL4LWiHineBBlNudschRHvbPaXMup15q2qFkGVLgq0fWUh5O0aednhmrZzEo5tA7ruU1dkdykhU5O5DcxVAI4HdV9F3O0Pe/Dztm3gRWSYlOwq4pAARuLXyBxk9mojBDH1FY2C3bwi9W+9s6jZqzH8wALL3h8HkWnOubpZ0lOrzk8oveBGWMXiZnsCwdJIBAn9fblbsm8dzLC3T2D5c6aJd7PhesiXyzbu+3tPNnOJF9qRRkOiaY7H0u/Qy3B6zzOyGygOIZ20D7PPrB9OXgoYQs0F6fHiAf6RPtHIa1BYVmlVr8UGCzl/yw704dNzBvUY+4wJUQnrbyF5SD+iF0iOfqX/HER5mt3FnckJ3DR145nHLDCKeBIzCS9frCsKhp1wpAre3SyeXI+UkhplJyTxAUX6vzJYst6Jxvk71AJT7zF+TJ1Q4gH811L/OzEKTKrs5OoRum5kMHRSLtDx68hOH73sU4kP6Koe6nFZp96+0+E2GrMDRCsB8K/yH5mGEavvvCISL+4GXOUl375F+J1bseqFjVk1yZjCTMxAX5maAxTS3DY+WZXVo7pF/dUTdcSfgyt6oxhfh7C65JxaGlF07OTMfNe2ptudU8DH3B7kXviasW5pyV2BN1SPefYrwRbwXFxRS
    username: AgAC+mDjt5pBgxGSQfQX0ru9DYYUdUab3UtDAUA7Ig0f2KBwfDmo9mBjAmskrLQCIcOW04lxjeF4Tx5g4dgt4KBqM+RXHB81EqvzXitfq13aUbrukeLhmBx4ozBshabyQG+RDMgdgyCmiVAqItpKuu/klCmUL+VctFjktI9AeflgqHw/e0RvlV78erbWjgHfrCL1eHJBPIfkucKzFKn5NZFgGlbPo6gqtKps1VIMEAM3b/niAFgarBOY4uW58DPjNxCossCVjc2WHin6HmMQV5xvdJinfqUh9SvkZtw+1dK3LjERLzcrUVSqDgsjXfLDRHHfhiXjj5DbCWt5+qBYKvLpydLkanaI06hV13JDuoZZe/RD7QveJxMWYGtjS2h73U8/7O1EQPpixadBdUJwSGUmF19LAGYzU3v11a563gmJJmG1sjK4yPQ9JKCyZvtv3ansmySZtZB6VEv2TzJzhLEvQ65eWxSUmoiGg/LqxQ48sMunixxduckQWTyojHh6SEys2A5pR9fZKu+6SvAPyiyDr6xd8GqzyBX3O2o583tzmm+b3neokMvNQ0206nX25Y7Uk8jS4iek6UXSVUZVKpC0r9GSKxvCRKr3Lt8hal9kMn1HXdq7QQHOSgELWW0RegoUXDYc0PQ09NW0ZU7Ch1OqgPmqF7qKEUtgKB8n+7NmXd0etQOfAtb1fowrfkh/IHei1oYDVw==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
