apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-multi-env
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mohammedd2510/argocd-gitops-repo-demo.git
        revision: HEAD
        directories:
          - path: environments/*

  template:
    metadata:
      name: "nginx-{{path.basename}}"
      labels:
        app: nginx
        env: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/argocd-gitops-repo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true